<?php
declare(strict_types=1);

// Phantomjscloud SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PhantomjscloudUtility::setRegistrar(function (PhantomjscloudUtility $u): void {
    $u->clean = [PhantomjscloudClean::class, 'call'];
    $u->done = [PhantomjscloudDone::class, 'call'];
    $u->make_error = [PhantomjscloudMakeError::class, 'call'];
    $u->feature_add = [PhantomjscloudFeatureAdd::class, 'call'];
    $u->feature_hook = [PhantomjscloudFeatureHook::class, 'call'];
    $u->feature_init = [PhantomjscloudFeatureInit::class, 'call'];
    $u->fetcher = [PhantomjscloudFetcher::class, 'call'];
    $u->make_fetch_def = [PhantomjscloudMakeFetchDef::class, 'call'];
    $u->make_context = [PhantomjscloudMakeContext::class, 'call'];
    $u->make_options = [PhantomjscloudMakeOptions::class, 'call'];
    $u->make_request = [PhantomjscloudMakeRequest::class, 'call'];
    $u->make_response = [PhantomjscloudMakeResponse::class, 'call'];
    $u->make_result = [PhantomjscloudMakeResult::class, 'call'];
    $u->make_point = [PhantomjscloudMakePoint::class, 'call'];
    $u->make_spec = [PhantomjscloudMakeSpec::class, 'call'];
    $u->make_url = [PhantomjscloudMakeUrl::class, 'call'];
    $u->param = [PhantomjscloudParam::class, 'call'];
    $u->prepare_auth = [PhantomjscloudPrepareAuth::class, 'call'];
    $u->prepare_body = [PhantomjscloudPrepareBody::class, 'call'];
    $u->prepare_headers = [PhantomjscloudPrepareHeaders::class, 'call'];
    $u->prepare_method = [PhantomjscloudPrepareMethod::class, 'call'];
    $u->prepare_params = [PhantomjscloudPrepareParams::class, 'call'];
    $u->prepare_path = [PhantomjscloudPreparePath::class, 'call'];
    $u->prepare_query = [PhantomjscloudPrepareQuery::class, 'call'];
    $u->graphql_body = [PhantomjscloudGraphql::class, 'body'];
    $u->graphql_errors = [PhantomjscloudGraphql::class, 'errors'];
    $u->result_basic = [PhantomjscloudResultBasic::class, 'call'];
    $u->result_body = [PhantomjscloudResultBody::class, 'call'];
    $u->result_headers = [PhantomjscloudResultHeaders::class, 'call'];
    $u->transform_request = [PhantomjscloudTransformRequest::class, 'call'];
    $u->transform_response = [PhantomjscloudTransformResponse::class, 'call'];
});
